### ISSUE TITLE
why use tolower() in taxon conversion

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#12]
@jpeters7 I see the L1-L3 uses tolower before matching the IL/IN L1_treeX column to the conversion table level1 column. Given we have the various capitalization varieties (e.g. 'w thorn', 'W thorn', 'W Thorn') in the conversion table, I'm going to change this not to use tolower() but let me know if I'm missing something.

**Comment by paciorek** [comment]
Also I see we have different conversion row for IL and IN. Should we be doing the taxon conversion in two pieces - one for IL and one for IN? I guess it is fine as is - I'm just removing any rows for which there is identical conversion L1->L3 info.

**Comment by jpeters7** [comment]
When I do my conversions, I make both the conversion table and the PLS taxa lower case because I had been missing some taxa due to difference in upper/lower case.  But I have updated the conversion table so it should have all the upper/lower case spellings that are in the PLS file.  However, it would be good to include a check that confirms this is true for all the domains. 
Also I think it is good to continue to do the taxon conversion in two pieces for IL and for IN. I can imagine a situation where we enter new data for one of the states and want to re-run this code but may not necessarily want to re-run for all the domains.

**Comment by paciorek** [comment]
done - I moved L1->L3 conversion in cjp_cleanup to occur before the IN/IL concatenation. Also put in a check for missing L1 values that could be due to capitalization issues.
