### ISSUE TITLE
logical issues in get_angle

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#14]
In the cjp_cleanup branch, I moved get_angle_IN into code/auxil.R (and renamed it get_angle_inil and also I put "_" in between 'bearing' and 'bearingdir' when I concatenated them).

@Kah5 can you look at my comments in that code in get_angle(). There are multiple places in the function where there are lines of code that can never have any effect, by definition of boolean arithmetic.

Also, I don't understand what is going on with the add/subtract 180/360 in the last few lines. Can you put into comments in the code what 'degrees' means, in particular given it is (mostly) restricted between 0 and 90. 

Why are no adjustments made to the degrees for the NE/SE/NW/SW cases? 

There seem to be 9 'degrees' values that are greater than 90. Thoughts on what to do with them?

**Comment by paciorek** [comment]
In looking back at Simon's original code, I see that 'uni' occurs when it's not ne/se/nw/sw, and is either n/s/e/w. @Kah5 perhaps just that the "!" in `!(north | south | east | west)` should not be there?

**Comment by paciorek** [comment]
Followup: based on other discussions, I think I now understand that NE and NW quadrant angles were relative to 0 = North and SE and SW quadrant angles were relative to 0 = South, hence the +/- 180/360. Would still be helpful to briefly document that, once the distinction between the N/S/E/W and NW/SW/NE/SE cases are clarified.

**Comment by Kah5** [comment]
After looking throught the code I agreen with @paciorek that the "!" in !(north | south | east | west) should not be there. Additionally, in the lines from 37 - 41, the first condition won't ever be true. I think this is a holdover from simon's witness tree code, but I am not sure that it could have been true there either. 

The end of the code should then convert the angles from 43 degrees SE to a 360 degree azimuth. There seems to be an error here too, since we never convert the "SE/SW/NE/NW" cases.
As far as commenting/making corrections, do you want to work on this or should I?

**Comment by paciorek** [comment]
@Kah5 - if you could rework the code (feel free to do in the master branch) with any needed assistance from @jpeters7  that would be great, since you understand the angle stuff in the data whereas I do not.

**Comment by Kah5** [comment]
Fixed the erroneous "!" in !(north | south | east | west), converted the angles from 0-90 degrees in each quadrant to a 360 degree azimuth

**Comment by paciorek** [comment]
Thanks, @Kah5 .  For now I am keeping Simon's get_angle for UMW as a separate function in cjp_cleanup branch, though I might merge them once I have the UMW data in front of me and can better understand the various special cases that need to be handled for UMW. So I am going to leave this open as a reminder for me.

**Comment by paciorek** [comment]
Ok, so there a still some unresolved issue with getting azimuths for IL/IN. @Kah5 or @jpeters7 please weigh in and based on the responses I will modify get_angle_inil in the cjp_cleanup branch.

1) What should we do when degrees > 90?  Right now we are just proceeding with the calculation even though that moves the value into a different quadrant. Is that ok?
2) We no longer check for 88888, 99999 in the get_angle_inil function, but we also never have replaced 88888 and 99999 with NA.  I'm guessing we should be doing that replacement so that, for example  N_NA and N_88888 are treated the same.
3) I want to confirm that if we have a bearing but not a degrees that we want azimuth to be NA, which is what the code is doing now. I haven't looked but I guess such points get thrown out eventually. Would we instead just want to assign an azimuth of 45,135,225,315 (depending on the quadrant) as a placeholder?

There are few issues around whether think of 0 as being a missing value to match the southern Michigan convention. In general, I think this is confusing and we should instead just convert the southern Michigan 0s to NAs.

1) if we have NA_NA for bearings (i.e., bearing combined with bearingdir), I presume we want azimuth=NA. But we have some where azimuth is 0. For clarity I'd like to set these to NA, presuming that that is what we want it to be.
4) Kelly set an azimuth of 360 when the bearing info suggests true North because of the 0=NA in southern Michigan. I'd rather just have these be 0. 
5) We have cases of being in the NE quadrant and having a bearingdir of 0. So that results in an azimuth of 0. This reinforces points above because it means we are not being consistent about setting all true 0s to be 360s.

**Comment by jpeters7** [comment]
@Kah5 - weigh in as well. But this is what I think.
1. I think we should make degrees >90 = NA.
2. This depends.  If we have N_NA as in N 0 NA 100 then we need to keep this because the tree is 100 links north of the post. Anytime we have a tree bearing in a cardinal direction we will have a 0 in the degrees column.  But if we have N 35 88888 100 then we do not know if the bearingdir is E or W.  But in these cases, the degrees should always be >0.
3. Yes. If we do not have degrees then the azimuth will be NA.  We could use the bearing and bearingdir to get the quadrant (i.e., N 88888 W 100 = NW quadrant.). But I think in the end if we don't have a degree, then we can't get the azimuth. @Kah5 what do you think?

I agree - I think it makes  more sense to convert the southern Michigan 0s to NAs
1. Agree
2. Agree
3. Agree

**Comment by Kah5** [comment]
1. Yeah, I think greater than 90 degrees should be set to NA
2. If we have 88888 or 99999 (missing data) then I think these should be NA as well
3. Yes if we are missing data for the degrees, then we can't get an azimuth and we don't estimate density at this corner. This is different from cases when we only have one direction given (N, S, E, or W), which should be denoted by 0 degrees. 

I agree that we should change the so. michigan 0's to NAs 

To fix some of these issues with NAs, I would propose that we estimate the 360 azimuths within the code, rather than using charlies estimated azim_360 columns.

**Comment by paciorek** [comment]
Not responding to all of this discussion but on the question of missing degrees when we do know the quadrant, I thought our only use of azimuth is to determine if the two trees are in the same quadrat, so it's not clear to me why we would throw out cases where we know the quadrat but not the exact azimuth.

**Comment by Kah5** [comment]
Yeah thats a good point, we should be able to use them to estimate density if we have a quadrant

**Comment by paciorek** [comment]
Summary of conclusion from phone conversation with @jpeters7 @Kah5 :+1: 

1) angle of 0 + (N|S|E|W) + NA = cardinal direction. Change the NA to "C" for cardinal
2) N|S + E|W + number = compute azimuth
3) any cases of 88888, 99999 should never occur with an angle of 0; all these should be treated as unknown azimuth
4) waiting on discussion with Charlie/Simon for angle <0 or >90.

**Comment by paciorek** [comment]
I didn't change NA to "C", but do now handle cases (1), (2), (3).

**Comment by paciorek** [comment]
Charlie is fixing <0, >90 for so MI.

Chris is treating <0, >90 in UMW as being in the indicated quadrant despite the angle.
