### ISSUE TITLE
assigning QQ (water) only for first two trees in MN

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#20]
This code only assigns QQ for first two trees. Given we use the 3rd/4th trees in some cases, it's not clear why this is only done for first two trees. 

@Kah5 @jpeters7 do either of you know?

```
minn$SP1 <- as.character(minn$SP1)
minn$SP2 <- as.character(minn$SP2)
minn$SP1[minn$VEGTYPE %in% c('L', 'M', 'S', 'R', 'A') & minn$SP1 %in% '_'] <- 'QQ'
minn$SP2[minn$VEGTYPE %in% c('L', 'M', 'S', 'R', 'A') & minn$SP2 %in% '_'] <- 'QQ'
```

**Comment by Kah5** [comment]
I am not sure why it is only done for the first two trees, but my best guess is that either these vegtypes only show up in the first two trees, or the assumption is that we remove the QQ points anyways

**Comment by jpeters7** [comment]
Because these corners are in water (as defined by the VEGTYPE 'L', 'M', 'S', 'R', and 'A') there will be no trees for SP1, SP2, SP3, and SP4.  So looking for the '_' in SP1 and SP2 will catch all the corners with water.  Since these corners will be removed. It is okay to put the 'QQ' in the SP1 and SP2 and not worry about putting them in SP3 or SP4.

**Comment by paciorek** [comment]
Ok, but logically given that 1 vs 2 vs 3 vs 4 has no real meaning, it's weird we are looking at sp1 and sp2 instead of looking only at sp1 (if all 4 will be '_') or looking at all of sp1, sp2, sp3, sp4.

**Comment by paciorek** [comment]
I did a check and in all cases with L,M,S,R,A, if sp1 == '_' then the other 3 trees are also '_'.
