### ISSUE TITLE
how to treat sec_corner in southern Michigan

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#26]
There are 4 values of 'Check' and 205 values of 'F'.

Currently these are being assigned 'internal'. Is  this what we want?

**Comment by jpeters7** [comment]
The 4 values of 'Check' should just be removed - I'll add the code following where the sMI data is loaded in 1_clean_merge_point_data.R. The two 'Check' corners in Branch and Livingston Counties fall in the middle of the sections instead of on the section or (1/4) section corners. Someday we can see if someone at UW can check the mylar maps for these, but for now, let's just remove them.  The two corners in Arenac County are corners that are closely adjacent along the Lake Huron shore where the section boundaries do not line up. 

The 205 'F' values should be kept.  These corners were labeled as 'F' (i.e., "flagged") because they are slightly shifted off from where they should fall on the corner/(1/4) section corners on the map. Jody talked to Jack and Simon and we agreed to keep these because we think that the shift happened when the mylar maps were georeferenced and because the data gets aggregated to the 8km scale, these shifts will most likely not affect the aggregation.
@paciorek I will update the southern MI csv to have list "Intsec" or "Extsec" and add notes that the corner is flagged because it is slightly shifted, then I'll push the new southern Michigan file to the wiki and update the name to the config file.

**Comment by jpeters7** [comment]
The southern MI corners where sec_corner = 'F' now have the sec_corner labeled as Extsec or Intsec given their location with the townships.  The new southernMI_projected_v1.3.csv file is on the wiki and the name is updated in the config file.
I have also included code in the 1_clean_merge_point_data.R to remove the four .southern MI corners where sec_corner = 'Check'
