### ISSUE TITLE
RECNUM_C in northern MI CSV converted to numeric

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#31]
Simon does this processing because the 'point' info is apparently incorrect.
``
nomi <- nomi %>% mutate(point = as.numeric(substr(recnum_c, 9, 11)))
``
But in the new CSV the recnum_c column is numeric and has lost digits of precision as it got converted to scientific notation.

@jpeters7 can you create an updated CSV in which that is output as character strings in quotes?
No need to renumber the version as no one should have done anything with the file yet.

**Comment by SimonGoring** [comment]
Just to be clear, it's because they're using a numeric to encode the spatial information that ncludes township information.

It's not that the point number is incorrect, it's because it comes in two parts from the Mich data, a regional code and then what we generally consider the point, which is the last 3 values.

**Comment by SimonGoring** [comment]
Yep, so in this case the `022` is the actual point number so that we can then figure out if it is a section or quarter section point.  I had to figure this out, but I can't find the place where I got this.  David Mladenoff might know how this fits into the system exactly (I think 11, 352, 723 may be the breakdown).

**Comment by jpeters7** [comment]
I'm confused, because in the michigan.filled.shp that I converted to a csv with xy coordinates in the Great Lakes St. Lawrence Albers projection, the recnum_c values are 0, but the recnum values match this pattern. Is there any reason we shouldn't be using recnum instead of recnum_c?

**Comment by jpeters7** [comment]
@SimonGoring - I went back to the michigan_filled.shp and compared the RECNUM and RECNUM_C column entries.  There are ~47k rows where both columns have the same entry.  There are ~40k rows where RECNUM has the 15 digit code and RECNUM_C has "0".  And there are ~8k rows where RECNUM has "0" and RECNUM_C has the 15 digit code.  My thought moving forward is to create one column that reflects the 15 digit code. 
Let me know if I am misinterpreting the file or if there is a different reason I should not move forward with this plan.

**Comment by jpeters7** [comment]
@paciorek, @SimonGoring - let me know how we should proceed with this.  
FIRST: I exported the attribute table from GIS which fixed the issue where we were losing the scientific notation. Now both RECNUM and RECNUM_C have all the digits and there is no longer extra 0s at the end of the number string.  However, there are entries where RECNUM has "0" but RECNUM_C has the number string and other entries where RECNUM_C has "0" but RECNUM has the number string and then finally other entries where both have the number string and it is the same number string.  @paciorek do you have a preference for moving forward - would you like a file with one RECNUM column or should we use the original file that has both RECNUM columns and then include in the R processing a selection for whichever column has the number string? 
SECOND: I created the file with all the RECNUM and RECNUM_C number strings are combined into one column RECNUM2. From this I checked out the substr() in R to see what unique values we were pulling.  I  used this code:
mi$RECNUM2 = as.character(mi$RECNUM2)
sub.recnum = as.data.frame(table((substr(mi$RECNUM2, 9, 11))))
The attached zip file includes the summary table and the Michigan data. Because I got counts for +13 and an e+1, I used excel to try to figure out what was going on.  In excel I used the Text to Columns option and added the count summary of those values to the attached summary table. 
@SimonGoring - what kind of numbers should we be seeing when we use substr(mi$RECNUM, 9,11)?

[northernmi_pls_projected_v1.2.zip](https://github.com/PalEON-Project/PLS_products/files/1919846/northernmi_pls_projected_v1.2.zip)

**Comment by jpeters7** [comment]
Never mind. I see that the pnt values do not correspond to the points listed in lines 514-521 of the cjp branch of the 1_clean_merge file.  So it does look like we want to substr() using characters 9-11.  BUT when I looked at the counts of those substr() points that match the section and external points listed in lines 514-521, I only get 44436 corners that have a value that matches those listed in lines 514-521. There are another 51706 corners that have substr() values that do not match any that are in that list.  So @SimonGoring is it correct that we should be removing over half of the Michigan data?

**Comment by SimonGoring** [comment]
I am pretty sure the `filled` file uses the data from the scanned sheets to fill the hole in the NP, so the spatial distribution of the points with 0 values in the REC should reflect that.  I'm really not sure what's going on here as far as the changes Jody's talking about though,

Are these changes related to specific commits on a branch in the repo Jody?

**Comment by jpeters7** [comment]
@SimonGoring - I think we are getting close to having this resolved!  But just want to double check two things: 1) that using both recnum and recnum_c to get the point values is appropriate and 2) get a copy of the point numbering system the upper midwest uses, because it is different than what we use for IL and IN.
For point 1) 
When I map the filled.shp points by which ones have values for recnum, which ones have values for recnum_c, and which have values for both I get the map below (yellow = values for recnum, blue = values for recnum_c, maroon = values for both). From what you are saying and from looking at the image below, it sounds like the mylar maps were scanned in two stages with some of the points having recnum values for one of those scans and some of the points having recnum values for the other scans.  
In your https://github.com/SimonGoring/WitnessTrees/blob/master/R/process_raw/step.one.clean.bind_v1.4.R in the Witness Trees repo, you use the michigan_filled.shp file but only use the substr() the recnum_c column (line 61 of that clean.bind.R file).  But, given that there are 0 values in the recnum_c column, I think we need to substr() both the recnum and the recnum_c columns.  
For point 2) 
Simon - can you send a key that lists all the point numbers and whether they are section or 1/4 section? There is a list of section numbers on line 514 in the cjp branch of this file in this repo (https://github.com/PalEON-Project/PLS_products/blob/cjp_cleanup/R/point_processing/1_clean_merge_point_data.R). But then there is a note that says all other point values are 1/4 section corners.  I'm not familiar with the point numbering system for the upper midwest. It is different than the way we number points for IL and IN. If you wouldn't mind sending me the numbering system, that would be great just so I can understand the upper midwest methods better.  But I think the point numbers go from 1-126?  If this is the case then we actually are good to keep moving forward to substr() the recnum and recnum_c columns (and we can ignore my previous comment).  When I do the substr() for both recnum and recnum_c values, all but 25 of the 96,000 points in Michigan have point numbers that fall between 1-126.


![recnum_michigan](https://user-images.githubusercontent.com/6137819/38933738-d7bb59ea-42e7-11e8-9f96-b401b3284432.png)

**Comment by paciorek** [comment]
I suppose it would be good to resolve this for posterity, but I just realized that I think the only way we use this info is for assigning correction factors and for northern MI, we use the same correction factor for all points, so none of this will affect any of our current calculations...

**Comment by paciorek** [comment]
Simon: don't worry about having info in both. Data from different data sources and coming from a merge.

Jody: would still like point info. Simon: go to Almendinger MN PDF. Simon will post.

**Comment by SimonGoring** [comment]
The plot numbers are in the last page of the [Minnesota's Bearing Tree Database](https://files.dnr.state.mn.us/eco/nhnrp/brgtree.pdf) PDF document, on the last page.

Minnesota’s Bearing Tree Database, by John Almendinger, Biological Report No. 56, Minnesota Department of Natural Resources, 1997.

**Comment by jpeters7** [comment]
@SimonGoring Thanks!
@paciorek - do you want me to add code to substr() the RECNUM/RECNUM_C or do you want to do that?

**Comment by paciorek** [comment]
@jpeters7 it looks like the no MI CSV file needs to be recreated with recnum and recnum_c saved as character variables. What I see now is numbers in scientific notation where we've lost the 9-11th digits in the conversion.

Given that incorrect labelling of 'section' vs. 'quarter-section' affects which correction factor is used,  I'm inclined to throw those points out during the point cleaning unless we have an informed guess as to whether they are section or quarter-section.

**Comment by jpeters7** [comment]
I added "format(mi$recnum, scientific=F)" to deal with the scientific notation with the recnum and recnum_c columns. Then re-ran the mutate(pmax) code and was able to get the same table listed above.  See if it works for you.  I agree, let's throw out the points that are >=127.

**Comment by paciorek** [comment]
I'm not understanding. The northernmi_pls_projected_v1.1.csv  file is storing the numbers in scientific notation with only ~6 significant digits. So most of the digits are zero after we do the `format(mi$recnum, scientific=F)` in the R code.  The issue is that the input CSV does not have the full set of digits, not with how we manipulate the field in the R code. 

I don't see how you get the table as listed above. I get this:
``
> table(nomi$point)

    0 
96142 
```

**Comment by jpeters7** [comment]
Given this issue and your other comment in issue #45 regarding missing FID numbers, I'm wondering if you must have the wrong northern MI file.  In the file I downloaded from the wiki just now, I have both FID values and the RECNUM values have more than 6 digits.

![image](https://user-images.githubusercontent.com/6137819/39828314-8656315e-5388-11e8-813b-521b1cdea6cd.png)

**Comment by paciorek** [comment]
Must have been a problem on my end with incorrect file. Redownloaded and things look fine.

**Comment by paciorek** [comment]
I do see 6 recnums that don't produce a non-zero point value:

 "12330830000000" "11380410000000" "11380410000000" "12350110000000" "12350110000000" "12350110000000"

Current plan is to remove these points in addition to the other ones where the value is outside 1-126.

**Comment by jpeters7** [comment]
Those are all good to remove. They have no data for trees, the township, county, etc.  There is only the FID, RECNUM, and xy coordinates.
