### ISSUE TITLE
angles > 90 in UMW

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#32]
@SimonGoring I'm looking at get_angle() for UMW and I'm not clear on a couple things.

1) We have various cases of angles > 90. Some of these seem to be used and some seem to be treated as NA. E.g., "S99W" is used as angle 99 with implicit transfer into a different quadrant. But something like "N388W" is not handled and therefore converted to NA. 

2) Did you treat cases with decimal points as NA purposefully? E.g., "S37.5W", "S13.3E". In principle we know what to do with this, but perhaps we don't trust a case where the surveyor seems overly precise.

Since we only use azimuths for determining whether two trees are in the same quadrant, is there an argument for simply ignoring the actual numerical angle and only looking for N,S,E,W?

**Comment by paciorek** [comment]
This issue is replicated in the email to Charlie and Simon 2018-04-12.

**Comment by paciorek** [comment]
Charlie does this for southern MI:

```
I have used a decision tree for southern Michigan: which goes as follows 1) if cardinal alphabetic directions (E, S, W, N) are given with no azimuth they are converted to 90, 180, 270, 360 bearings (note N is 360 not 0 which is a hard zero for  no recorded direction of any kind).  If two alphabetic directions are given with no azimuth (NE, SE, SW, NW either together or in azimuth columns 1,3) these are retained and a 45 azimuth is inserted between them. If one of these ordinals is missing with an azimuth, a logical substitution (correct typos, complete quadrants or put on same side for external corners or opposite side for internal corners) is inserted.  A 0 azimuth (soft 0) with cardinal directions is accommodated as above. A 0 ordinal direction is problematic, but follows as above. Azimuths below 0 are converted to positive values and the quadrant remains as indicated by alphabetic direction. Azimuths of 90 are converted to cardinal (E or W) bearing. Azimuths above 90 are checked for obvious typos --double numbers, sticky finger (adjacent numbers on keyboard)-- and corrected. If two alphabetic directions are given in a logically consistent quadrant and the azimuth is still greater than 90, a 45 azimuth is substituted.  Otherwise (seldom) the corner is ignored for quadrant or pair angle correction. 
```
The analog for UMW without going through the level of detail that Charlie looked into things in terms of interpreting individual values is to treat the alphabetic quadrant info as correct when provided and never use the angle to move the 360 degree azimuth to a new quadrant. @paciorek will implement this.

**Comment by jpeters7** [comment]
There was one more set of decisions that Charlie included. I'm adding this comment to that listed above, so it is all in one comment here.

Charlie's decision tree for southern MI:
I have used a decision tree for southern Michigan: which goes as follows 1) if cardinal alphabetic directions (E, S, W, N) are given with no azimuth they are converted to 90, 180, 270, 360 bearings (note N is 360 not 0 which is a hard zero for  no recorded direction of any kind).  If two alphabetic directions are given with no azimuth (NE, SE, SW, NW either together or in azimuth columns 1,3) these are retained and a 45 azimuth is inserted between them. If one of these ordinals is missing with an azimuth, a logical substitution (correct typos, complete quadrants or put on same side for external corners or opposite side for internal corners) is inserted.  A 0 azimuth (soft 0) with cardinal directions is accommodated as above. A 0 ordinal direction is problematic, but follows as above. Azimuths below 0 are converted to positive values and the quadrant remains as indicated by alphabetic direction. Azimuths of 90 are converted to cardinal (E or W) bearing. Azimuths above 90 are checked for obvious typos --double numbers, sticky finger (adjacent numbers on keyboard)-- and corrected. If two alphabetic directions are given in a logically consistent quadrant and the azimuth is still greater than 90, a 45 azimuth is substituted.  Otherwise (seldom) the corner is ignored for quadrant or pair angle correction.  If the azimuth is > 3 digits and distance is 0, the numerals are redistributed in the most parsimonious way.  Also an observation for many of the negative values are 999 (or 888) azimuths, so these must be stripped before any calculation and typically 45 entered.
