### ISSUE TITLE
most info for third and fourth trees in IN/IL missing

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#4]
I know we don't use this info, but seems weird that in a few cases it is recorded but not in all cases.

**Comment by paciorek** [comment]
Actually perhaps we do if distances are not in increasing order for trees 1, 2, 3, 4? (I'm still working through what happens with the 'ranked.data' calculation.
But for IL, DIST4 is set to NA.

**Comment by jpeters7** [comment]
The surveyors don't always list 3rd and 4th trees in IL and IN. Usually, they only list 2 trees.  When they list 1 or 3 trees there are sometimes notes that say "no other trees near" or "no tree near in the 4th quadrant".

**Comment by paciorek** [comment]
Can I remove the setting of DIST4 to NA (this line is only for IL, so not clear to me why we would want to do this)?

**Comment by jpeters7** [comment]
@Kah5 - we should look at this when we meet on Wednesday.  I think we want to pick the two closest trees out of all the trees listed so I don't think we want to set DIST4 automatically to NA.  But another thing for us to talk about are the trees set on the corner.  When there are trees set on the corner I think we want to use the other trees listed because I assume the trees on the corners will make the density really big (since Simon notes that trees 1-2 feet away from the corner make the density really big).  Not sure what to do when there is only one tree listed and it is a corner tree - this may go into the conversation we need to have with @SimonGoring and Charlie about the 1 tree corners.

**Comment by Kah5** [comment]
We only use the two closest corners in In and IL. I think the original file was reading in as all NaNs, but we needed it to be NAs.  I think we fixed that issue. We can look at this on Wednesday.

**Comment by paciorek** [comment]
We don't want to set IL$DIST4 to NA because it might be one of first two trees in distance. Removing this from the code.
