### ISSUE TITLE
holes in southern Michigan

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#44]
@jpeters7 These holes in so. MI are expected ,right?
![so_mich](https://user-images.githubusercontent.com/2501598/39263664-b96b951e-4877-11e8-9cf6-07fe598251d5.jpg)

**Comment by jpeters7** [comment]
Yes. Those holes were there when I originally got the southern MI data from Simon.  I assume the mylar maps for those locations were not available.

**Comment by SimonGoring** [comment]
Do we have a township list?

**Comment by paciorek** [comment]
Simon and Jody may take a look to confirm these holes are expected.

**Comment by paciorek** [comment]
@jpeters7 I think we resolved this, right? Can you comment and close this issue if that seems like the thing to do?

**Comment by jpeters7** [comment]
@paciorek these were missing from the mylars. But I was just looking at the land notes and they are available. I have 33 townships listed above. However, that list of 33 includes townships that are already partially filled in. There are approximately 12 full townships that would need to be entered and georeferenced.  I can have the undergrads focus on entering those 12 townships immediately. Then we would have to think about whether to include the additional partial townships since students would need to sort through the corner notes for those townships to get the missing corners.  To do the 12 townships, I think it would take about a month to get the data entered and georeferenced. Would you want to wait that long? And are you okay with not getting the data for the ~15 townships with partial data.

**Comment by paciorek** [comment]
@jpeters7 In the manuscript I say that the field notes for these areas are missing. Can you clarify whether they are or are not available and if needed fix the text in the manuscript?

**Comment by paciorek** [comment]
We say this in the manuscript:

"Fig. 1 shows some townships with no survey points. Spot checks indicate these are generally caused by missing data from the original surveys, with the original field notes not being available for unknown reasons. "

I'm closing, this, but @jpeters7 if there is anything wrong with the language please fix in the manuscript draft.

**Comment by jpeters7** [comment]
This text about the missing data is correct!
