### ISSUE TITLE
revisiting one-tree points

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#5]
This issue is a placeholder for what will probably need to be a discussion with @SimonGoring and Charlie. 

Some comments:
1) ~3.5% of points (1924 one-tree points) with trees in IN are one-tree points (i.e., NA in the info for second tree); about 10% are no-tree
~5.5% in IL are one-tree points (3086 one-tree points); about 49% are no-tree

2) Of the one-tree points, 505 in IN and 250 in IL have 0 as the distance to the first tree. This is disconcerting and makes me uncertain about the following idea.

One idea for dealing with one tree points is to make a guess as to how far a surveyor would go for a second tree and compute density based on one tree in that guesstimate area. This then allows us to account for the fact that biomass at one tree points is low for the one taxon found and 0 for all others.

**Comment by paciorek** [comment]
Follow up that same issues will occur in UMW so we will want to be consistent.

**Comment by jpeters7** [comment]
@paciorek - @Kah5 and I talked about this and agree we need a conversation with @SimonGoring and Charlie. Right now these 1-tree points are removed in all the data after we estimate density.

**Comment by paciorek** [comment]
Jody to look for pattern for one-tree points with 0 distance - in terms of whether they are particular kinds of points. 

We might want to get Charlie's input.

One possibilty is to disgard the 0-distance 1-tree points and keep the others.

**Comment by paciorek** [comment]
CJP to look for 1-tree 0-distance points in SoMI and UMW.

**Comment by jpeters7** [comment]
I looked at the 1 tree points with 0 distance for IL and IN. I was expecting to see them in the prairie area where the trees were more spread apart and that adjacent corners that did have trees would have those trees far from the corner (>100 links - this is a random cutoff, if we need something more defensible, I can get the distribution of distances. Right now I'm just selecting the corners around the 1 tree-0 distance corners and scanning the distances of the trees in the adjacent corners).  I also thought that these 0 distance trees could be clustered by township due to the way specific surveyors did their surveys.  
Here's what I found. In IL and IN combined, there are 685 corners (out of 77766 corners with trees) that have 1 tree and its distance is 0.  Instead of being in prairie areas, these corners are actually more in the forested areas of both states and are often clustered by township.  I think the 1 tree 0 corner reflect surveyor method rather than prairie areas. When these 1 tree-0 distance corners are in areas of mixed prairie/forests, the surrounding corners typically have distances to their trees between 5-50-ish links not the far distances of >100 links as I had expected.  I think we should not include these 1 tree with 0 distance corners in the analyses. Make these be NAs.  
There are 220 corners that have 2 trees with one of the two being a 0 distance tree and the other having a tree with distance >0. Of the 220 corner, 207 have the 0 distance tree listed as tree1 and 13 have the 0 distance tree listed as tree2.  Depending on if we decide we can use 1-tree points to estimate density, I think we should treat these 220 corners as 1 tree points.  There are 50 corners with three trees listed where either the first tree is the 0 distance tree or the third tree is the 0 distance tree, but for these 50 corners, we do have distances for 2 trees, so should treat these as we do for the normal two-tree density estimates.

**Comment by paciorek** [comment]
I think I am ok with throwing out the 0-distance 1-tree points on account of surveyor weirdness.

I'm not particularly comfortable with treating 2-tree points with a 0-distance tree as a 1-tree point. The 0-distance tree implies a high density while a 1-tree point implies a low density. 

I guess we need to schedule a discussion with Charlie (and Simon if he can/wants to join) to discuss 1-tree points in general and also 0-distance trees in their various forms.

**Comment by paciorek** [comment]
Next steps:

- throw out points with 1 tree at 0 distance. This is likely because tree was the corner and no other trees were looked for/recorded.
- for other 1-tree points we will impute a density equal to some reasonable upper bound based on how far the surveyors might have searched. This is likely to be something like 200-300 links but we will check the empirical distribution of distances for further guidance.
