### ISSUE TITLE
Isle  Royale corners marked as 'Check'

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#59]
@jpeters7 are we still simply filtering out corners marked as 'Check' in the sec_corner field in southern MI?  I can do this in my code, but for a dataset release we should probably have you do that before these get into the cleaned public data.

**Comment by jpeters7** [comment]
@paciorek I don't see any "Check" entries in the sec_corner for the version 1.5 data.  These should all be fixed.

**Comment by paciorek** [comment]
Sorry, they are actually in the Isle Royale data. Can you take a look?

**Comment by jpeters7** [comment]
The Check corners are the highlighted ones in the image below that a) fall in Lake Superior or b) are located on the Island that have 2 entries side by side that need to be checked.  
For this version of the biomass model, I suggest we take out the Isle Royale data. We had kept it in because we are aggregating to the 8km scale and thought the corners off the Island are most likely corners that should be located on the Island. 
But I do think it would be worth asking Charlie or getting one of our ND undergrads to go through the field notes and check to see which data entries are correct and which ones need to be deleted or added.  Then we can format the updated dataset to match the northern MI format and add it for a future version 1.3.    
![image](https://user-images.githubusercontent.com/6137819/47029205-f561c800-d138-11e8-92d2-8fc7f3fe9ed0.png)

**Comment by paciorek** [comment]
At this point given I have code in place, I think it might be easiest to just remove the Check and Check-Double points and leave the others in place, since we have used Isle Royale in other products/versions.

**Comment by jpeters7** [comment]
Okay. Do you want to do that with the code or do you want me to remove and update the v1.1 supplement file on the wiki?

**Comment by paciorek** [comment]
I'll just do it with code for now, since I think we think that the cleaned version for NIS will incorporate the Detroit work that is ongoing, right?

**Comment by jpeters7** [comment]
Yep that's right. I'll check with Charlie to see if he has the bandwidth to do Isle Royale and if not I'll have an undergrad work on it. Then we can add any corrections when we update Detroit.

**Comment by jpeters7** [comment]
Charlie checked the mylars and the blue corners in Lake Superior are correct, they have just been shifted from the land to out in the water.  I think you could leave in the "Check" corners. I would still take out the "Check - double" entries which have two entries at similar locations.  We'll fix the georeferencing issues when we add the Detroit data.

**Comment by paciorek** [comment]
@jpeters7 just want to check if for our next round of the raw data, we plan to fix (a) the Isle Royale locations  and (b) de-duplicate the 'check-double' entries.

**Comment by jpeters7** [comment]
Our student checked out the Isle Royale data. Of the 49 corners he checked in the notes, only 18 (37%) of them had the correct information.  Another 19 corners (39%) had all information incorrect and 12 (24 %) corners had information that was partially correct (e.g., diameters or azimuths didn't match up between the corner data from the mylars and the PLS notes).  Since there are so many discrepancies and since the georeferenced mylar data has corners located in Lake Superior, I think we should remove these corners from our analyses and put it on ND's list of townships to re-enter. There are a number of partial townships with data for the Island, but in reality it would only be entering about 10 full townships worth of data.  Our ND students could get that done in a couple of weeks. I don't think it is worth waiting for for the next biomass model run, but we should put it on ND's list of things to do moving forward.

**Comment by paciorek** [comment]
Closing this given decision to omit Isle Royale pending re-entry by ND.
