### ISSUE TITLE
'water' or 'wet' points not excluded

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#6]
It looks like current code is setting stem density to 0 for such points but not excluding them. 

I believe we want to treat 'No tree' as 0 density and 0 biomass and 'Water' or 'Wet' as no information because we don't want to dampen our spatially-smoothed estimates by the water points. I.e., our estimate will be density or biomass estimates per unit of land area. 

I plan to exclude 'Water' or 'Wet' points in the very first step of processing (point_processing/1_clean_merge_point_data.R) but would like any comments from @SimonGoring @Kah5 @jpeters7 if I am overlooking something that makes this a bad idea.

**Comment by paciorek** [comment]
CJP to remove water/wet for IL/IN in cjp_cleanup; @Kah5 to do for SoMI.

**Comment by Kah5** [comment]
Removed water and wet trees in so. mich and INIL in master. There was only one "Water" point in so mich, but this had a Basswood for Species1 and Water listed for Species2. Strangely, it had a diameter for both tree 1 and tree 2. The level 1 species listing was "creek". This might be a point that @jpeters7 and myself might need to double check, so I am not closing this issue just yet

**Comment by jpeters7** [comment]
Huh. @Kah5 you're right.  I didn't catch that before.  Because the basswood is listed at tree1 and there is diameter and bearing information for the creek, that makes me think this might actually be a tree but we don't know what species it is.  When surveyors mark creeks in IL and IN they will often give the width of the creek and the direction it goes (e.g., "creek 10 links wide courses SW"), but this entry has the azimuth and distance given.  I think we leave it is as an unknown tree or take the corner out.

**Comment by jpeters7** [comment]
INIL should be good (Kelly removed it in the master, so not sure if it has been transferred to the cjp-branch).
For southern MI we need to decide whether to have "creek" be unknown tree and treat as a 2 tree point with a basswood and an unknown tree. Or remove the entry from the analysis because we don't know what the "creek" is referring to...  Since there is diameter, quadrant, azimuth, and distance information for this entry, I am leaning towards marking "creek" as Unknown tree in Level3a.

**Comment by paciorek** [comment]
Sure, if only one case, let's make it 'unknown tree'

**Comment by jpeters7** [comment]
I updated the level0_to_level3a_v0.4-8.csv to convert "creek" to "Unknown tree". The conversion file has been uploaded to the wiki.
