### ISSUE TITLE
recnum numeric digits lost in northern MI v1.5

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#60]
@jpeters7 we need you to save v1.5 CSV as you did with previous version so that all digits of recnum field are preserved. I'm seeing scientific notation in v1.5 whereas in v1.4 all digits were present.

**Comment by jpeters7** [comment]
@paciorek the recnum is only in the northernmi data which is v1.2. it is not in the southermi data which is v1.5.  
For some reason when I save the csvs or upload to GIS the recnum gets truncated.  Since I added new corner data, we have ~4000 records that do not hvae recnum or recnum_c values, but the new ones do have pnt values which is what I think you are trying to get from the 9-11 digits in the recnum values.  Could I instead select the pnt digits 9-11 from the recnum/recnum_c and we use that instead? 
We seem to continually have issues with the scientific notation for the recnum/recnum_c values and if we convert to pnt that will eliminate that issue.
However, if you prefer the recnum/recnum_c values, I can join those for the entries that we have them and we'll use the pnt values for the 4000.

**Comment by jpeters7** [comment]
@paciorek - update after I slept on this and did a bit of work this morning.
I have a conversion file with the FID values, recnum values (recnum, recnum_c, and newrecnum following your code from the 1_clean_merge to create the newrecnum column), and the point numbers (whic I got by selecting characters 9-11 from newrecnum). 
I was looking through the point values and found a number that fell outside the 1-120 value point range we expect. 
I checked these and found 23 entries are extra entries that are not on a section or 1/4 section corner (but a nearby entry is in the correct location) an oftentimes has no tree information. I added these 23 entries to the northernMI_todelete.csv and have deleted them from the northern MI v1.2 file.  
There are 6 entries that were removed previously and are no longer in the v1.2 file, so will not be an issue when the points or recnums are joined to the v1.2 data.  7 entries had point values that were not possible (e.g., >120), I found these locations on the map and entered the correct point value (e.g., point had been 270, is actually 27; had been 658, is actually 85, etc).  
To finalize the northern MI v1.2 file, let me know if you prefer to have the recnum and recnum_c values or if we can add the point values.  I know having the recnum values can be nice to give consistency between version numbers. But if people are actually going to be using these data, the recnum values are so hard to work with and having the point value make it very easy to locate the point if someone wants to go back to the field notes.  For example, if Charlie had the point values, it would have made his efforts to find the field notes easier.

**Comment by paciorek** [comment]
@jpeters7 I'm happy to have you change over to point values.

**Comment by jpeters7** [comment]
Great! I'll make the change now.

**Comment by jpeters7** [comment]
I have uploaded the updated northernMI v1.5 to the wiki which now has the recnum values no longer truncated and the "pnt" column now has the updated point values for all entries.  @paciorek you shouldn't need to run the following code anymore in the 1_clean_merge file:

nomi <- nomi %>% mutate(newrecnum = format(pmax(recnum,recnum_c), scientific = FALSE))  ## format prevents NAs when 9-11 digits are 0s
nomi <- nomi %>% mutate(point = as.numeric(substr(newrecnum, 9, 11)))

Instead you should be able to use "pnt" column to get the point values.
