### ISSUE TITLE
lower-case versus upper-case Water/Wet/water/wet in IN/IL

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#68]
In the versions of IN/IL from last fall, wet corners had either Water or Wet in L1_tree1. There were no cases of water or wet.

In the new versions, most of the IN corners are Water or Wet, but there are now 48 water points.
And now almost all of IL points are water or wet, but there are 3 Water.

Easy enough for me to detect. But given that I thought ND was simply adding IL points, it makes me nervous that values for corners that were in the older version of the data are changing, even if only capitalization.

@jpeters7 any idea what is happening?

**Comment by paciorek** [comment]
Similar issue with "No tree" versus "no tree". Formerly everything was "No tree".
This seems to be messing with the use of level 1 to level 3a conversions, so ideally this would be fixed on your end @jpeters7 .

**Comment by paciorek** [comment]
And in looking a bit more, it looks like almost all (but not all) of L1 values in new IL data have been converted to all lower case.

**Comment by jpeters7** [comment]
Yes, the lower case values happened when I updated our Quality Control code. I made all entries in L1_tree# lower case and removed periods because when I was doing the checks there were so many different versions of the same name that it was really difficult to go through the list of potential L1 entries to make sure they made sense  (e.g., w oak could be W oak, W Oak, w oak, w. oak, W. oak, W. Oak).  If you use the L3_tree1 values they should all be listed as Water, Wet, No tree and No data and not have the capitalization issues.

**Comment by paciorek** [comment]
1) So in IL we have both "No tree/no tree", "No data/no data", and "Water/water", as well as "W ok" and maybe a few others capitalized.

IN and Detroit still have a lot of capitalized entries in L1.

Is this all as you expect/want?

2) I'm not sure what you mean by "use L3_tree1". We exclude Water/Wet based on L1. "Water" and "Wet" don't appear in the L1 column in the level0 to level3a conversion file. So I need to strip out water corners before converting to L3. It's fine if I should look for Water/water, Wet/wet to decide what corners to remove but just want to be clear on this.

**Comment by paciorek** [comment]
And just as a reminder - I never use the L3 columns provided in the raw data. I use L1 and the level0 to level3a conversion file to produce L3. Just want to make sure that is correct in your mind and doesn't introduce any problems.

**Comment by jpeters7** [comment]
First - one correction on what I wrote above. After looking back at my code, I do not remove any "." from the names.  As for the capitalization, the mix of uppercase and lowercase is fine and is expected.  It is a result of the changes in the QA/QC code as we have continued to enter data.  For IN, the capitalized entries are either ones that were entered in a previous version or for version 1.8 are entries that I double checked the notes and corrected manually and didn't keep the lowercase format.  For Detroit, since there were a smaller number of townships entered there weren't as many taxa to convert, so I kept the capitalization as it was.  For IL, could you double check the L1 trees/entries you are reading in?  When I looked at the most recent v1.9 data uploaded to the wiki, all the L1 trees had been converted to lowercase.  

I agree using the L1_tree1 values of No data/no data, Water/water, etc is the best way to go to strip the Water, Wet, No tree, and No data entries.  I had suggested using L3 from the raw data because I thought that might be easy. But with the way you have set up the code you only read in the L1 tree data, so it is better to add upper and lower case options for the Water, Wet, No tree, and No data entries rather than bringing in the L3 raw data.  I think having you re-do the L1 to L3 conversion using the level0 to level3a conversion code is the correct way to go and won't introduce any problems.

**Comment by paciorek** [comment]
Ok, in IL v. 1.9, I see 
2 White Oak
3 Water 
1 W ok
243 No tree
96 No data

**Comment by jpeters7** [comment]
Ah - sorry about that. I was scrolling through the taxa instead of putting them in a table.  You are correct.  We should be good to move forward with using upper and lowercase options for the Water, Wet, No tree, and No data entries to stip those corners.
