### ISSUE TITLE
L3 columns are in raw Detroit datafile (and in Indiana)

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#69]
I think we agreed that L3 columns would not be in the csv files that are the gold raw data files from ND. The detroit file does have L3 (as does Indiana, which has been the case for Indiana in the past). Not a big deal if they stay in, but just flagging this. Note that 1_clean_merge_point_data.R ignores (and overwrites) and L3 columns.

**Comment by jpeters7** [comment]
Yes, we did. But when I do the Quality Control check I convert to L3 taxa as a way to find which L1 taxa need to be added to the level0_to_level3a conversion file and to get the updated counts for those taxa for that table.  So since I am adding the L3 taxa anyway, I thought I would leave that in the file that we are uploading to the wiki. This is also useful for students who are working with these files in our lab.  And actually, the v1.9 Illinois data now have L3 taxa listed as well...  If you don't mind just overwriting the current L3 columns, I think that would be the best way to go.

**Comment by paciorek** [comment]
fine by me.
