### ISSUE TITLE
change MN/WI XA, XB, XC codes to "No data"

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#74]
@jpeters7 in looking at David M's codes, I think we should treat XA, XB, XC as the corner is missing and have the conversion table set level3a to "No data" and all the "D?" and XX codes as "Missing" meaning "missing tree".  In a small number of cases I think we can use corners that have one or more of the D?/XX codes if they don't occur in the nearest two trees. 

How does that sound?

**Comment by jpeters7** [comment]
I changed XA, XB, and XC in the level0 to leve3a v0.8 conversion file. I think leaving all the "D?" codes as missing makes sense. I wonder if we should change the XX to No data instead of leaving as Missing.  I'm not exactly sure what "Indeterminable" means. But it seems that if it is indeterminable then we don't have data for that corner.

**Comment by paciorek** [comment]
Sure I think having XX as "No data" makes sense. As per issue #71 it doesn't look to me like the changes have been made in the v0.8 file on the Wiki.

**Comment by jpeters7** [comment]
Done!

**Comment by paciorek** [comment]
@jpeters7 please keep XX as Missing. I see in the data that where we have trees marked as XX, there are other trees at those corners that have data. And we are taking "No data" to mean no data at entire corner. So that is not right for the XX case.

**Comment by jpeters7** [comment]
Changed XX to Missing and uploaded to the Wiki.
