### ISSUE TITLE
do we use data with missing years and how choose correction factors in IN and IL

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#9]
IN and IL have 'year' coded as 9999 (not it's not 99999, which is what the code currently checks for).

@Kah5 it looks like you might want to set the surveyyear for points with missing years to be 'ALL'? Is that correct?  And that we then use those data?

Or perhaps we just want to find the nearest point with a non-missing year and assign that year? 

In IN, it looks like the 9999's are in a haphazard pattern but the known years of survey occur in spatial blocks, so this seems fairly safe.

For IL, it's mostly the same story but the 1840-1850 data do include some points that are scattered amongst points from earlier decades.

**Comment by jpeters7** [comment]
Almost all the year information that is missing from either the S or E borders of townships where the year could not be found in the PLS notes.  Looking at the data, I agree that we can use the nearest points to estimate the missing years for most of the data, especially since our correction factors for IL and IN are split for surveys before or after 1825.  In IN the pattern is quite clear for the 1825 cut off (early surveys in the south later surveys in the north) and the points with missing year information fall neatly in within that pattern.  As you mention @paciorek, for IL it seems reasonable that most points with missing year information should have the year cut off be the same as the rest of the data from the township where the year information is missing.  However, in IL we have more townships where one or both borders are surveyed before or after 1825 and the interior is surveyed in the opposite time period.  There are two townships (27N13W2 and 21N6E3) where the missing year information are in borders that are near other townships with borders that were surveyed before or after 1825 while the interior was surveyed in the opposite time period. These townships, I am not as confident about which year category to put them in.  I'm not sure how big of a difference that will make on the density estimates though.

**Comment by paciorek** [comment]
ok, thanks for context here. I think it is better to impute a year than to throw the data out.

@jpeters7  can you suggest what imputation method we should use (same year as others in township, same year as nearest, some other approach)?

**Comment by jpeters7** [comment]
I think we should use the same year as others in the township.

**Comment by jpeters7** [comment]
@Kah5 and I talked about this and looked at the distribution of years together today.  We decided that using the date from the closest corner would be better than the year as others in the same township because there can be multiple years in the same township. Kelly is going to add code to the IL and IN sections that does this.  We also looked at the corners in IL in the two townships that were close to other townships with borders with year values that are different than the interior years.  Those corners have no trees so they won't be included in the density estimates anyways.

**Comment by paciorek** [comment]
@Kah5 added code for this. 

@paciorek to see if this issue arises for SoMI and UMW.

**Comment by paciorek** [comment]
there are limited numbers of points in the various domains that are missing years and in all cases, seems reasonable to assign the year of the nearest point, particularly given the years get lumped into long time periods to determine from amongst a small number of correction factors.
